language: python
python:
- 2.7
sudo: false

cache:
  directories:
  - $HOME/google-cloud-sdk/

env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin
  PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # decrypt credentials
- openssl aes-256-cbc -K $encrypted_2cb3533d089c_key -iv $encrypted_2cb3533d089c_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "${GAE_PYTHONPATH}" ]; then python scripts/fetch_gae_sdk.py $(dirname
  "${GAE_PYTHONPATH}"); fi
- gcloud config set project `geoscixyz`
